// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import (
	accounts "github.com/ethereum/go-ethereum/accounts"
	address "github.com/filecoin-project/go-address"

	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	context "context"

	ecdsa "crypto/ecdsa"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// FEVMActions is an autogenerated mock type for the FEVMActions type
type FEVMActions struct {
	mock.Mock
}

type FEVMActions_Expecter struct {
	mock *mock.Mock
}

func (_m *FEVMActions) EXPECT() *FEVMActions_Expecter {
	return &FEVMActions_Expecter{mock: &_m.Mock}
}

// AgentAddMiner provides a mock function with given fields: ctx, agentAddr, minerAddr, ownerWallet, ownerAccount, ownerPassphrase, requesterKey
func (_m *FEVMActions) AgentAddMiner(ctx context.Context, agentAddr common.Address, minerAddr address.Address, ownerWallet accounts.Wallet, ownerAccount accounts.Account, ownerPassphrase string, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, minerAddr, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, minerAddr, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, minerAddr, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, minerAddr, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentAddMiner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentAddMiner'
type FEVMActions_AgentAddMiner_Call struct {
	*mock.Call
}

// AgentAddMiner is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - minerAddr address.Address
//   - ownerWallet accounts.Wallet
//   - ownerAccount accounts.Account
//   - ownerPassphrase string
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentAddMiner(ctx interface{}, agentAddr interface{}, minerAddr interface{}, ownerWallet interface{}, ownerAccount interface{}, ownerPassphrase interface{}, requesterKey interface{}) *FEVMActions_AgentAddMiner_Call {
	return &FEVMActions_AgentAddMiner_Call{Call: _e.mock.On("AgentAddMiner", ctx, agentAddr, minerAddr, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)}
}

func (_c *FEVMActions_AgentAddMiner_Call) Run(run func(ctx context.Context, agentAddr common.Address, minerAddr address.Address, ownerWallet accounts.Wallet, ownerAccount accounts.Account, ownerPassphrase string, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentAddMiner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(address.Address), args[3].(accounts.Wallet), args[4].(accounts.Account), args[5].(string), args[6].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentAddMiner_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentAddMiner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentAddMiner_Call) RunAndReturn(run func(context.Context, common.Address, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentAddMiner_Call {
	_c.Call.Return(run)
	return _c
}

// AgentBorrow provides a mock function with given fields: ctx, agentAddr, poolID, amount, ownerWallet, ownerAccount, ownerPassphrase, requesterKey
func (_m *FEVMActions) AgentBorrow(ctx context.Context, agentAddr common.Address, poolID *big.Int, amount *big.Int, ownerWallet accounts.Wallet, ownerAccount accounts.Account, ownerPassphrase string, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, poolID, amount, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *big.Int, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, poolID, amount, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *big.Int, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, poolID, amount, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, *big.Int, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, poolID, amount, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentBorrow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentBorrow'
type FEVMActions_AgentBorrow_Call struct {
	*mock.Call
}

// AgentBorrow is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - poolID *big.Int
//   - amount *big.Int
//   - ownerWallet accounts.Wallet
//   - ownerAccount accounts.Account
//   - ownerPassphrase string
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentBorrow(ctx interface{}, agentAddr interface{}, poolID interface{}, amount interface{}, ownerWallet interface{}, ownerAccount interface{}, ownerPassphrase interface{}, requesterKey interface{}) *FEVMActions_AgentBorrow_Call {
	return &FEVMActions_AgentBorrow_Call{Call: _e.mock.On("AgentBorrow", ctx, agentAddr, poolID, amount, ownerWallet, ownerAccount, ownerPassphrase, requesterKey)}
}

func (_c *FEVMActions_AgentBorrow_Call) Run(run func(ctx context.Context, agentAddr common.Address, poolID *big.Int, amount *big.Int, ownerWallet accounts.Wallet, ownerAccount accounts.Account, ownerPassphrase string, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentBorrow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(*big.Int), args[4].(accounts.Wallet), args[5].(accounts.Account), args[6].(string), args[7].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentBorrow_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentBorrow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentBorrow_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, *big.Int, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentBorrow_Call {
	_c.Call.Return(run)
	return _c
}

// AgentChangeMinerWorker provides a mock function with given fields: ctx, agentAddr, minerAddr, workerAddr, controlAddrs, ownerWallet, ownerAccount, ownerPassphrase
func (_m *FEVMActions) AgentChangeMinerWorker(ctx context.Context, agentAddr common.Address, minerAddr address.Address, workerAddr address.Address, controlAddrs []address.Address, ownerWallet accounts.Wallet, ownerAccount accounts.Account, ownerPassphrase string) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, minerAddr, workerAddr, controlAddrs, ownerWallet, ownerAccount, ownerPassphrase)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, address.Address, []address.Address, accounts.Wallet, accounts.Account, string) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, minerAddr, workerAddr, controlAddrs, ownerWallet, ownerAccount, ownerPassphrase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, address.Address, []address.Address, accounts.Wallet, accounts.Account, string) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, minerAddr, workerAddr, controlAddrs, ownerWallet, ownerAccount, ownerPassphrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, address.Address, address.Address, []address.Address, accounts.Wallet, accounts.Account, string) error); ok {
		r1 = rf(ctx, agentAddr, minerAddr, workerAddr, controlAddrs, ownerWallet, ownerAccount, ownerPassphrase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentChangeMinerWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentChangeMinerWorker'
type FEVMActions_AgentChangeMinerWorker_Call struct {
	*mock.Call
}

// AgentChangeMinerWorker is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - minerAddr address.Address
//   - workerAddr address.Address
//   - controlAddrs []address.Address
//   - ownerWallet accounts.Wallet
//   - ownerAccount accounts.Account
//   - ownerPassphrase string
func (_e *FEVMActions_Expecter) AgentChangeMinerWorker(ctx interface{}, agentAddr interface{}, minerAddr interface{}, workerAddr interface{}, controlAddrs interface{}, ownerWallet interface{}, ownerAccount interface{}, ownerPassphrase interface{}) *FEVMActions_AgentChangeMinerWorker_Call {
	return &FEVMActions_AgentChangeMinerWorker_Call{Call: _e.mock.On("AgentChangeMinerWorker", ctx, agentAddr, minerAddr, workerAddr, controlAddrs, ownerWallet, ownerAccount, ownerPassphrase)}
}

func (_c *FEVMActions_AgentChangeMinerWorker_Call) Run(run func(ctx context.Context, agentAddr common.Address, minerAddr address.Address, workerAddr address.Address, controlAddrs []address.Address, ownerWallet accounts.Wallet, ownerAccount accounts.Account, ownerPassphrase string)) *FEVMActions_AgentChangeMinerWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(address.Address), args[3].(address.Address), args[4].([]address.Address), args[5].(accounts.Wallet), args[6].(accounts.Account), args[7].(string))
	})
	return _c
}

func (_c *FEVMActions_AgentChangeMinerWorker_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentChangeMinerWorker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentChangeMinerWorker_Call) RunAndReturn(run func(context.Context, common.Address, address.Address, address.Address, []address.Address, accounts.Wallet, accounts.Account, string) (*types.Transaction, error)) *FEVMActions_AgentChangeMinerWorker_Call {
	_c.Call.Return(run)
	return _c
}

// AgentConfirmMinerWorkerChange provides a mock function with given fields: ctx, agentAddr, minerAddr, pk
func (_m *FEVMActions) AgentConfirmMinerWorkerChange(ctx context.Context, agentAddr common.Address, minerAddr address.Address, pk *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, minerAddr, pk)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, minerAddr, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, minerAddr, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, address.Address, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, minerAddr, pk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentConfirmMinerWorkerChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentConfirmMinerWorkerChange'
type FEVMActions_AgentConfirmMinerWorkerChange_Call struct {
	*mock.Call
}

// AgentConfirmMinerWorkerChange is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - minerAddr address.Address
//   - pk *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentConfirmMinerWorkerChange(ctx interface{}, agentAddr interface{}, minerAddr interface{}, pk interface{}) *FEVMActions_AgentConfirmMinerWorkerChange_Call {
	return &FEVMActions_AgentConfirmMinerWorkerChange_Call{Call: _e.mock.On("AgentConfirmMinerWorkerChange", ctx, agentAddr, minerAddr, pk)}
}

func (_c *FEVMActions_AgentConfirmMinerWorkerChange_Call) Run(run func(ctx context.Context, agentAddr common.Address, minerAddr address.Address, pk *ecdsa.PrivateKey)) *FEVMActions_AgentConfirmMinerWorkerChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(address.Address), args[3].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentConfirmMinerWorkerChange_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentConfirmMinerWorkerChange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentConfirmMinerWorkerChange_Call) RunAndReturn(run func(context.Context, common.Address, address.Address, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentConfirmMinerWorkerChange_Call {
	_c.Call.Return(run)
	return _c
}

// AgentCreate provides a mock function with given fields: ctx, owner, operator, request, wallet, account, passphrase
func (_m *FEVMActions) AgentCreate(ctx context.Context, owner common.Address, operator common.Address, request common.Address, wallet accounts.Wallet, account accounts.Account, passphrase string) (*types.Transaction, error) {
	ret := _m.Called(ctx, owner, operator, request, wallet, account, passphrase)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, common.Address, accounts.Wallet, accounts.Account, string) (*types.Transaction, error)); ok {
		return rf(ctx, owner, operator, request, wallet, account, passphrase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, common.Address, accounts.Wallet, accounts.Account, string) *types.Transaction); ok {
		r0 = rf(ctx, owner, operator, request, wallet, account, passphrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Address, common.Address, accounts.Wallet, accounts.Account, string) error); ok {
		r1 = rf(ctx, owner, operator, request, wallet, account, passphrase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentCreate'
type FEVMActions_AgentCreate_Call struct {
	*mock.Call
}

// AgentCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - owner common.Address
//   - operator common.Address
//   - request common.Address
//   - wallet accounts.Wallet
//   - account accounts.Account
//   - passphrase string
func (_e *FEVMActions_Expecter) AgentCreate(ctx interface{}, owner interface{}, operator interface{}, request interface{}, wallet interface{}, account interface{}, passphrase interface{}) *FEVMActions_AgentCreate_Call {
	return &FEVMActions_AgentCreate_Call{Call: _e.mock.On("AgentCreate", ctx, owner, operator, request, wallet, account, passphrase)}
}

func (_c *FEVMActions_AgentCreate_Call) Run(run func(ctx context.Context, owner common.Address, operator common.Address, request common.Address, wallet accounts.Wallet, account accounts.Account, passphrase string)) *FEVMActions_AgentCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Address), args[3].(common.Address), args[4].(accounts.Wallet), args[5].(accounts.Account), args[6].(string))
	})
	return _c
}

func (_c *FEVMActions_AgentCreate_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentCreate_Call) RunAndReturn(run func(context.Context, common.Address, common.Address, common.Address, accounts.Wallet, accounts.Account, string) (*types.Transaction, error)) *FEVMActions_AgentCreate_Call {
	_c.Call.Return(run)
	return _c
}

// AgentPay provides a mock function with given fields: ctx, agentAddr, poolID, amount, senderKey, requesterKey
func (_m *FEVMActions) AgentPay(ctx context.Context, agentAddr common.Address, poolID *big.Int, amount *big.Int, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, poolID, amount, senderKey, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, poolID, amount, senderKey, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, poolID, amount, senderKey, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, poolID, amount, senderKey, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentPay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentPay'
type FEVMActions_AgentPay_Call struct {
	*mock.Call
}

// AgentPay is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - poolID *big.Int
//   - amount *big.Int
//   - senderKey *ecdsa.PrivateKey
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentPay(ctx interface{}, agentAddr interface{}, poolID interface{}, amount interface{}, senderKey interface{}, requesterKey interface{}) *FEVMActions_AgentPay_Call {
	return &FEVMActions_AgentPay_Call{Call: _e.mock.On("AgentPay", ctx, agentAddr, poolID, amount, senderKey, requesterKey)}
}

func (_c *FEVMActions_AgentPay_Call) Run(run func(ctx context.Context, agentAddr common.Address, poolID *big.Int, amount *big.Int, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentPay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(*big.Int), args[4].(*ecdsa.PrivateKey), args[5].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentPay_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentPay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentPay_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentPay_Call {
	_c.Call.Return(run)
	return _c
}

// AgentPullFunds provides a mock function with given fields: ctx, agentAddr, amount, miner, senderKey, requesterKey
func (_m *FEVMActions) AgentPullFunds(ctx context.Context, agentAddr common.Address, amount *big.Int, miner address.Address, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, amount, miner, senderKey, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, amount, miner, senderKey, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, amount, miner, senderKey, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, amount, miner, senderKey, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentPullFunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentPullFunds'
type FEVMActions_AgentPullFunds_Call struct {
	*mock.Call
}

// AgentPullFunds is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - amount *big.Int
//   - miner address.Address
//   - senderKey *ecdsa.PrivateKey
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentPullFunds(ctx interface{}, agentAddr interface{}, amount interface{}, miner interface{}, senderKey interface{}, requesterKey interface{}) *FEVMActions_AgentPullFunds_Call {
	return &FEVMActions_AgentPullFunds_Call{Call: _e.mock.On("AgentPullFunds", ctx, agentAddr, amount, miner, senderKey, requesterKey)}
}

func (_c *FEVMActions_AgentPullFunds_Call) Run(run func(ctx context.Context, agentAddr common.Address, amount *big.Int, miner address.Address, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentPullFunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(address.Address), args[4].(*ecdsa.PrivateKey), args[5].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentPullFunds_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentPullFunds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentPullFunds_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentPullFunds_Call {
	_c.Call.Return(run)
	return _c
}

// AgentPushFunds provides a mock function with given fields: ctx, agentAddr, amount, miner, senderWallet, senderAccount, senderPassphrase, requesterKey
func (_m *FEVMActions) AgentPushFunds(ctx context.Context, agentAddr common.Address, amount *big.Int, miner address.Address, senderWallet accounts.Wallet, senderAccount accounts.Account, senderPassphrase string, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, amount, miner, senderWallet, senderAccount, senderPassphrase, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, amount, miner, senderWallet, senderAccount, senderPassphrase, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, amount, miner, senderWallet, senderAccount, senderPassphrase, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, amount, miner, senderWallet, senderAccount, senderPassphrase, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentPushFunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentPushFunds'
type FEVMActions_AgentPushFunds_Call struct {
	*mock.Call
}

// AgentPushFunds is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - amount *big.Int
//   - miner address.Address
//   - senderWallet accounts.Wallet
//   - senderAccount accounts.Account
//   - senderPassphrase string
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentPushFunds(ctx interface{}, agentAddr interface{}, amount interface{}, miner interface{}, senderWallet interface{}, senderAccount interface{}, senderPassphrase interface{}, requesterKey interface{}) *FEVMActions_AgentPushFunds_Call {
	return &FEVMActions_AgentPushFunds_Call{Call: _e.mock.On("AgentPushFunds", ctx, agentAddr, amount, miner, senderWallet, senderAccount, senderPassphrase, requesterKey)}
}

func (_c *FEVMActions_AgentPushFunds_Call) Run(run func(ctx context.Context, agentAddr common.Address, amount *big.Int, miner address.Address, senderWallet accounts.Wallet, senderAccount accounts.Account, senderPassphrase string, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentPushFunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(address.Address), args[4].(accounts.Wallet), args[5].(accounts.Account), args[6].(string), args[7].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentPushFunds_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentPushFunds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentPushFunds_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, address.Address, accounts.Wallet, accounts.Account, string, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentPushFunds_Call {
	_c.Call.Return(run)
	return _c
}

// AgentRefreshRoutes provides a mock function with given fields: ctx, agentAddr, senderKey
func (_m *FEVMActions) AgentRefreshRoutes(ctx context.Context, agentAddr common.Address, senderKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, senderKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, senderKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, senderKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, senderKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentRefreshRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentRefreshRoutes'
type FEVMActions_AgentRefreshRoutes_Call struct {
	*mock.Call
}

// AgentRefreshRoutes is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - senderKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentRefreshRoutes(ctx interface{}, agentAddr interface{}, senderKey interface{}) *FEVMActions_AgentRefreshRoutes_Call {
	return &FEVMActions_AgentRefreshRoutes_Call{Call: _e.mock.On("AgentRefreshRoutes", ctx, agentAddr, senderKey)}
}

func (_c *FEVMActions_AgentRefreshRoutes_Call) Run(run func(ctx context.Context, agentAddr common.Address, senderKey *ecdsa.PrivateKey)) *FEVMActions_AgentRefreshRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentRefreshRoutes_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentRefreshRoutes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentRefreshRoutes_Call) RunAndReturn(run func(context.Context, common.Address, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentRefreshRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// AgentRemoveMiner provides a mock function with given fields: ctx, agentAddr, minerAddr, newOwnerAddr, senderKey, requesterKey
func (_m *FEVMActions) AgentRemoveMiner(ctx context.Context, agentAddr common.Address, minerAddr address.Address, newOwnerAddr address.Address, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, minerAddr, newOwnerAddr, senderKey, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, minerAddr, newOwnerAddr, senderKey, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, address.Address, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, minerAddr, newOwnerAddr, senderKey, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, address.Address, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, minerAddr, newOwnerAddr, senderKey, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentRemoveMiner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentRemoveMiner'
type FEVMActions_AgentRemoveMiner_Call struct {
	*mock.Call
}

// AgentRemoveMiner is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - minerAddr address.Address
//   - newOwnerAddr address.Address
//   - senderKey *ecdsa.PrivateKey
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentRemoveMiner(ctx interface{}, agentAddr interface{}, minerAddr interface{}, newOwnerAddr interface{}, senderKey interface{}, requesterKey interface{}) *FEVMActions_AgentRemoveMiner_Call {
	return &FEVMActions_AgentRemoveMiner_Call{Call: _e.mock.On("AgentRemoveMiner", ctx, agentAddr, minerAddr, newOwnerAddr, senderKey, requesterKey)}
}

func (_c *FEVMActions_AgentRemoveMiner_Call) Run(run func(ctx context.Context, agentAddr common.Address, minerAddr address.Address, newOwnerAddr address.Address, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentRemoveMiner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(address.Address), args[3].(address.Address), args[4].(*ecdsa.PrivateKey), args[5].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentRemoveMiner_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentRemoveMiner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentRemoveMiner_Call) RunAndReturn(run func(context.Context, common.Address, address.Address, address.Address, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentRemoveMiner_Call {
	_c.Call.Return(run)
	return _c
}

// AgentWithdraw provides a mock function with given fields: ctx, agentAddr, receiver, amount, senderKey, requesterKey
func (_m *FEVMActions) AgentWithdraw(ctx context.Context, agentAddr common.Address, receiver common.Address, amount *big.Int, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, receiver, amount, senderKey, requesterKey)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, receiver, amount, senderKey, requesterKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, receiver, amount, senderKey, requesterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Address, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, receiver, amount, senderKey, requesterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_AgentWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentWithdraw'
type FEVMActions_AgentWithdraw_Call struct {
	*mock.Call
}

// AgentWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - receiver common.Address
//   - amount *big.Int
//   - senderKey *ecdsa.PrivateKey
//   - requesterKey *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) AgentWithdraw(ctx interface{}, agentAddr interface{}, receiver interface{}, amount interface{}, senderKey interface{}, requesterKey interface{}) *FEVMActions_AgentWithdraw_Call {
	return &FEVMActions_AgentWithdraw_Call{Call: _e.mock.On("AgentWithdraw", ctx, agentAddr, receiver, amount, senderKey, requesterKey)}
}

func (_c *FEVMActions_AgentWithdraw_Call) Run(run func(ctx context.Context, agentAddr common.Address, receiver common.Address, amount *big.Int, senderKey *ecdsa.PrivateKey, requesterKey *ecdsa.PrivateKey)) *FEVMActions_AgentWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Address), args[3].(*big.Int), args[4].(*ecdsa.PrivateKey), args[5].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_AgentWithdraw_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_AgentWithdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_AgentWithdraw_Call) RunAndReturn(run func(context.Context, common.Address, common.Address, *big.Int, *ecdsa.PrivateKey, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_AgentWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// IFILApprove provides a mock function with given fields: ctx, spender, allowance, pk
func (_m *FEVMActions) IFILApprove(ctx context.Context, spender common.Address, allowance *big.Int, pk *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, spender, allowance, pk)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, spender, allowance, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, spender, allowance, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, spender, allowance, pk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_IFILApprove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IFILApprove'
type FEVMActions_IFILApprove_Call struct {
	*mock.Call
}

// IFILApprove is a helper method to define mock.On call
//   - ctx context.Context
//   - spender common.Address
//   - allowance *big.Int
//   - pk *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) IFILApprove(ctx interface{}, spender interface{}, allowance interface{}, pk interface{}) *FEVMActions_IFILApprove_Call {
	return &FEVMActions_IFILApprove_Call{Call: _e.mock.On("IFILApprove", ctx, spender, allowance, pk)}
}

func (_c *FEVMActions_IFILApprove_Call) Run(run func(ctx context.Context, spender common.Address, allowance *big.Int, pk *ecdsa.PrivateKey)) *FEVMActions_IFILApprove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_IFILApprove_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_IFILApprove_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_IFILApprove_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_IFILApprove_Call {
	_c.Call.Return(run)
	return _c
}

// IFILTransfer provides a mock function with given fields: ctx, receiver, amount, pk
func (_m *FEVMActions) IFILTransfer(ctx context.Context, receiver common.Address, amount *big.Int, pk *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, receiver, amount, pk)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, receiver, amount, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, receiver, amount, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, receiver, amount, pk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_IFILTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IFILTransfer'
type FEVMActions_IFILTransfer_Call struct {
	*mock.Call
}

// IFILTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - receiver common.Address
//   - amount *big.Int
//   - pk *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) IFILTransfer(ctx interface{}, receiver interface{}, amount interface{}, pk interface{}) *FEVMActions_IFILTransfer_Call {
	return &FEVMActions_IFILTransfer_Call{Call: _e.mock.On("IFILTransfer", ctx, receiver, amount, pk)}
}

func (_c *FEVMActions_IFILTransfer_Call) Run(run func(ctx context.Context, receiver common.Address, amount *big.Int, pk *ecdsa.PrivateKey)) *FEVMActions_IFILTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_IFILTransfer_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_IFILTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_IFILTransfer_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_IFILTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// InfPoolDepositFIL provides a mock function with given fields: ctx, agentAddr, amount, pk
func (_m *FEVMActions) InfPoolDepositFIL(ctx context.Context, agentAddr common.Address, amount *big.Int, pk *ecdsa.PrivateKey) (*types.Transaction, error) {
	ret := _m.Called(ctx, agentAddr, amount, pk)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) (*types.Transaction, error)); ok {
		return rf(ctx, agentAddr, amount, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) *types.Transaction); ok {
		r0 = rf(ctx, agentAddr, amount, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) error); ok {
		r1 = rf(ctx, agentAddr, amount, pk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FEVMActions_InfPoolDepositFIL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfPoolDepositFIL'
type FEVMActions_InfPoolDepositFIL_Call struct {
	*mock.Call
}

// InfPoolDepositFIL is a helper method to define mock.On call
//   - ctx context.Context
//   - agentAddr common.Address
//   - amount *big.Int
//   - pk *ecdsa.PrivateKey
func (_e *FEVMActions_Expecter) InfPoolDepositFIL(ctx interface{}, agentAddr interface{}, amount interface{}, pk interface{}) *FEVMActions_InfPoolDepositFIL_Call {
	return &FEVMActions_InfPoolDepositFIL_Call{Call: _e.mock.On("InfPoolDepositFIL", ctx, agentAddr, amount, pk)}
}

func (_c *FEVMActions_InfPoolDepositFIL_Call) Run(run func(ctx context.Context, agentAddr common.Address, amount *big.Int, pk *ecdsa.PrivateKey)) *FEVMActions_InfPoolDepositFIL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int), args[3].(*ecdsa.PrivateKey))
	})
	return _c
}

func (_c *FEVMActions_InfPoolDepositFIL_Call) Return(_a0 *types.Transaction, _a1 error) *FEVMActions_InfPoolDepositFIL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FEVMActions_InfPoolDepositFIL_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int, *ecdsa.PrivateKey) (*types.Transaction, error)) *FEVMActions_InfPoolDepositFIL_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFEVMActions interface {
	mock.TestingT
	Cleanup(func())
}

// NewFEVMActions creates a new instance of FEVMActions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFEVMActions(t mockConstructorTestingTNewFEVMActions) *FEVMActions {
	mock := &FEVMActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
