name: Go Daily Termination Tests

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1

      - name: Test
        run: go test -v ./terminate
        env:
          LOTUS_DIAL_ADDR: ${{ secrets.LOTUS_DIAL_ADDR }}
          LOTUS_TOKEN: ${{ secrets.LOTUS_TOKEN }}